# Generated by Django 5.0.3 on 2024-03-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='r_conference',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='core_1.meetups'),
        ),
    ]
