# Generated by Django 5.0.3 on 2024-03-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_1', '0002_alter_user_r_conference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetups',
            new_name='Meetup',
        ),
    ]
